services:
  www:
    build:
      dockerfile: ./d.brookebrodack-site.Dockerfile
    env_file:
      - .env
    expose:
      - "80"
      - "443"
      - "4020"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.services.brookebrodack-site.loadbalancer.server.port=4020"
      - "traefik.http.routers.brookebrodack-site.rule=Host(`${HOST:-bb.briantakita.me}`)"
      - "traefik.http.routers.brookebrodack-site.tls.certresolver=acme"
      - "traefik.http.middlewares.test-retry.retry.attempts=4"
      - "traefik.http.middlewares.test-retry.retry.initialinterval=100ms"
    networks:
      - web
    volumes:
      - .:/app
networks:
  web:
    external: true
