services:
  www:
    build:
      dockerfile: ./d.brookebrodack-site.Dockerfile
    env_file:
      - .env
    expose:
      - "80"
      - "443"
      - "4101"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.services.brookebrodack-site.loadbalancer.server.port=4101"
      - "traefik.http.routers.brookebrodack-site.rule=Host(`${HOST:-bb.briantakita.me}`)"
      - "traefik.http.routers.brookebrodack-site.tls.certresolver=acme"
      - "traefik.http.middlewares.brookebrodack-site.retry.attempts=4"
      - "traefik.http.middlewares.brookebrodack-site.retry.initialinterval=100ms"
    networks:
      - web
    volumes:
      - .:/app
    restart: on-failure
networks:
  web:
    external: true
